_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 55
                - 86
                - 92
                - 105
            "2":
                - 55
                - 86
                - 92
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
chunk_overlap:
    value: 200
chunk_size:
    value: 1000
model_name:
    value: exaone3.5:latest
prompt_type:
    value: default
retriever_k:
    value: 1
timestamp:
    value: "20250326_142535"
